package br.com.join.testAppJoin.validator;

import br.com.join.testAppJoin.entity.Category;
import org.springframework.stereotype.Component;

import javax.xml.bind.ValidationException;

@Component
public class CategoryControllerRequestValidator {

    private String ERROR_CATEGORY__NEW_PRODUCT_WITH_ID = "ID is autogenerated. Remove product ID.";

    public void validateRequest(Category category) throws ValidationException {

        if (category.getId() != null){
            throw new ValidationException(ERROR_CATEGORY__NEW_PRODUCT_WITH_ID);
        }
    }
}
