package br.com.join.testAppJoin.validator;

import br.com.join.testAppJoin.entity.Product;
import org.springframework.stereotype.Component;

import javax.xml.bind.ValidationException;

@Component
public class ProductControllerRequestValidator {

    private String ERROR_PRODUCT__NEW_PRODUCT_WITH_ID = "ID is autogenerated. Remove product ID.";
    private String ERROR_PRODUCT__NEW_PRODUCT_WITH_NO_CATEGORY = "Every product needs a category. Insert category ID";

    public void validateRequest(Product product) throws ValidationException {

        if (product.getId() != null){
            throw new ValidationException(ERROR_PRODUCT__NEW_PRODUCT_WITH_ID);
        }
        if (product.getCategory() == null ||
                product.getCategory().getId() == null ||
                product.getCategory().getId() <= 0L ){
            throw new ValidationException(ERROR_PRODUCT__NEW_PRODUCT_WITH_NO_CATEGORY);
        }
    }
}
